language: python
sudo: required

python:
  - "3.8"

before_install:
  - "python setup.py install"
  - script/travis_setup

script:
  - script/travis_test

jobs:
  include:
    - stage: distribute
      if: branch = main AND type != pull_request
      install: skip
      script:
        - script/distribute