# Experiment Information
experiment:
  name: "experiment_CIFAR10_Benchmark_backpropagaation_resnet20"
  output_dir: "trained_models"

# Dataset
dataset:
  name: "cifar10_benchmark"

# Model
model:
  architecture: "resnet20"
  mode: "backpropagation"
  pretrained: false
  # checkpoint:

# Training Parameters
training:
  hyperparameters:
    epochs: 160
    batch_size: 128
    target_size: 32

  optimizer:
    type: "SGD"
    lr: 0.1
    weight_decay: 0.0001
    momentum: 0.9

  lr_scheduler:
    type: "multistep_lr"
    gamma: 0.1
    milestones: [90, 130]

  metrics:
    top_k: 5
    display_iterations: 500

  loss_function:
    name: "cross_entropy"


# Infrastructure
infrastructure:
  num_gpus: 2
