# Experiment Information
experiment:
  name: "experiment_CIFAR10_Benchmark_sign_2_resnet20_test_3"
  output_dir: "trained_models"

# Dataset
dataset:
  name: "cifar10_benchmark"

# Model
model:
  architecture: "resnet20"
  mode: "sign_2"
  pretrained: false
  # checkpoint:

# Training Parameters
training:
  hyperparameters:
    epochs: 300
    batch_size: 128
    target_size: 32

  optimizer:
    type: "SGD"
    lr: 0.01
    weight_decay: 0.0001
    momentum: 0.9

  lr_scheduler:
    type: "multistep_lr"
    gamma: 0.1
    milestones: [100, 200, 250]

  metrics:
    top_k: 5
    display_iterations: 500

  loss_function:
    name: "cross_entropy"


# Infrastructure
infrastructure:
  num_gpus: 1
