# Experiment Information
experiment:
  name: "resnet_56_hook"
  output_dir: "trained_models"

# Dataset
dataset:
  name: "cifar10_benchmark"

# Model
model:
  architecture: "resnet56"
  mode: "sign_1"
  pretrained: false
  # checkpoint:

# Training Parameters
training:
  hyperparameters:
    epochs: 150
    batch_size: 128
    target_size: 32

  optimizer:
    type: "SGD"
    lr: 0.0001
    weight_decay: 0.00001
    momentum: 0.9

  lr_scheduler:
    type: "multistep_lr"
    gamma: 0.1
    milestones: [40, 80, 100]

  metrics:
    top_k: 5
    display_iterations: 300

  loss_function:
    name: "cross_entropy"


# Infrastructure
infrastructure:
  gpus: 1
