version: 2
jobs:
  test:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - biotorch-{{ checksum "setup.py" }}-{{ checksum "requirements.txt" }}
            - biotorch-
      - run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install --upgrade -r requirements.txt
      - save_cache:
          key: biotorch-{{ checksum "setup.py" }}-{{ checksum "requirements.txt" }}
          paths:
            - venv
      - run:
          name: Run tests
          command: . venv/bin/activate && script/circle_test
          no_output_timeout: 1h
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  version: 2
  test_package:
    jobs:
      - test
