# Experiment Information
experiment:
  name: "test_resnet_20_fa"
  output_dir: "trained_models"
  # For reproducibility
  seed: 2021
  deterministic: false

# Dataset
data:
  dataset: "cifar10_benchmark"
  dataset_path: null
  target_size: 32

# Model
model:
  architecture: "resnet20"
  mode:
    type: "fa"
    options:
      constrain_weights: false
      scaling_factor: true
      gradient_clip:

  pretrained: false
  # checkpoint:
  loss_function:
    name: "cross_entropy"

# Training Parameters
training:
  hyperparameters:
    epochs: 250
    batch_size: 128

  optimizer:
    type: "SGD"
    lr: 0.1
    weight_decay: 0.0001
    momentum: 0.9

  lr_scheduler:
    type: "multistep_lr"
    gamma: 0.1
    milestones: [100, 150, 200]

  metrics:
    top_k: 5
    display_iterations: 500

# Infrastructure
infrastructure:
  gpus: 3

evaluation: true
