# Experiment Information
experiment:
  name: "experiment_CIFAR10_Benchmark_backpropagaation_resnet56"
  output_dir: "trained_models"
  # For reproducibility
  seed: 2021
  deterministic: false

# Dataset
data:
  dataset: "cifar10_benchmark"
  dataset_path: null
  target_size: 32
  batch_size: 128

# Model
model:
  checkpoint: "/home/albert/projects/biotorch/trained_models/experiment_CIFAR10_Benchmark_sign_2_resnet20_test/model_best_acc.pth"
  loss_function:
    name: "cross_entropy"

# Infrastructure
infrastructure:
  gpus: 3

evaluation: true
