# Experiment Information
experiment:
  name: "CIFAR10_FA_Benchmark"
  output_dir: "trained_models"

# Dataset
dataset:
  name: "cifar10"

# Model
model:
  architecture: "resnet18"
  mode: "fa"
  pretrained: false
  # checkpoint:

# Training Parameters
training:
  hyperparameters:
    epochs: 10
    batch_size: 64
    target_size: 224

  optimizer:
    type: "RMSProp"
    lr: 0.001
    weight_decay: 0
    momentum: 0

  metrics:
    top_k: 5
    display_iterations: 500

  loss_function:
    name: "cross_entropy"


# Infrastructure
infrastructure:
  num_gpus: 1
