# Experiment Information
experiment:
  name: "MNIST Benchmark"
  output_dir: "trained_models"

# Dataset
dataset:
  name: "mnist"

# Model
model:
  architecture: "resnet18"
  mode: "fa"
  pretrained: false
  # checkpoint:

# Training Parameters
training:
  hyperparameters:
    epochs: 10
    batch_size: 32
    image_size: 32

  optimizer:
    'type': "RMSProp"
    'lr': 0.001

# Infrastructure
infrastructure:
  num_gpus: 1
